# Generated by Django 4.1.7 on 2023-10-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='head_of_departmemt',
            new_name='head_of_department',
        ),
    ]
