# Generated by Django 4.1.7 on 2023-10-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0002_rename_head_of_departmemt_department_head_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'other')], max_length=100, null=True),
        ),
    ]
