# Generated by Django 4.1.7 on 2023-10-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Male', 'Female'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
