# Generated by Django 4.1.7 on 2023-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
