# Generated by Django 4.1.7 on 2023-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0005_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
