# Generated by Django 4.2.6 on 2023-11-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
